# name: docker image build
# on: push

# defaults:
#     run:
#         shell: bash
# concurrency:
#     group: ${{github.workflow}}
#     cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps: 
#         - name: リポジトリ情報を取得する
#           uses: actions/checkout@v4
#         - name: build kitのセットアップ
#           uses: docker/setup-buildx-action@v3
#         - name: Build and push
#           id: build
#           uses: docker/build-push-action@v5
#           with:
#             context: .
#             outputs: type=image,name=test,push-by-digest=true,name-canonical=true,push=true