name: docker image build push
description: buildxでdocker imageの作成、追加
inputs:
  dockerfile-context:
    default: '.'
    required: false
    description: dockerfileの場所
  build-args:
    default: |
      JFROG_USERNAME=user
      JFROG_PWD=password
    required: false
    description: imageのbuild時に使用する環境変数
  image-repository:
    required: true
    description: imageの保存先
runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ GITHUB_ACTOR }}
        password: ${{ env.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/${{ GITHUB_REPOSITORY_OWNER}}/${{ env.IMAGE_NAME}}
        tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags}}
        labels: ${{ steps.meta.outputs.labels}}
        build-args: |
            JFROG_USERNAME=user
            JFROG_PWD=password