name: github packages docker image build push
on : push


env:
    IMAGE_NAME: hono-image

defaults:
    run:
        shell: bash
concurrency:
    group: ${{ github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build-push:
        runs-on: arc-runner-set
        permissions:
            contents: read # ソースコードのチェックアウトを許可
        container:
            image: docker:27.3.1
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - uses: docker/metadata-action@v5
              id: meta
              with:
                images: ghcr.io
                tags: |
                    type=sha,prefix={{branch}}-
            - uses: docker/build-push-action@v5
              with:
                push: true
                context: .
                tags: ${{ steps.meta.outputs.tags}}
                labels: ${{ steps.meta.outputs.labels}}
                build-args: |
                    JFROG_USERNAME=user
                    JFROG_PWD=password