name: github packages docker image build push
on : push


env:
    IMAGE_NAME: hono-image

concurrency:
    group: ${{ github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build-push:
        runs-on: dind
        permissions:
            contents: read # ソースコードのチェックアウトを許可
        timeout-minutes: 5
        container:
            image: node:bullseye-slim
        services:
            docker:
                image: docker:dind
        steps:
            - run: |
                sudo apt update
                curl -fsSL get.docker.com -o get-docker.sh
                sh get-docker.sh
                docker info
            - run: |
                node -v
                sleep 3600