name: github packages docker image build push
on : push


env:
    IMAGE_NAME: hono-image

defaults:
    run:
        shell: bash
concurrency:
    group: ${{ github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build-push:
        runs-on: ubuntu-22.04
        permissions:
            contents: read # ソースコードのチェックアウトを許可
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - run: |
                docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" secretlint/secretlint secretlint --maskSecrets '**/*'