name: github packages docker image build push
on : push


env:
    IMAGE_NAME: hono-image

concurrency:
    group: ${{ github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build-push:
        runs-on: dind
        permissions:
            contents: read # ソースコードのチェックアウトを許可
        timeout-minutes: 5
        container:
            image: docker:27
        services:
            node:
                image: node:bullseye-slim
        steps:
            - run: |
                docker container ls