name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: echo
        run: |
          echo "-------GITHUB_WORKSPACE----------"
          echo ${GITHUB_WORKSPACE}
          echo "-------github.workspace----------"
          echo ${{github.workspace}}
          echo "---------------------------------"
          printenv
  test2:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu
    steps:
      - name: echo
        run: |
          echo "-------GITHUB_WORKSPACE----------"
          echo ${GITHUB_WORKSPACE}
          echo "-------github.workspace----------"
          echo ${{github.workspace}}
          printenv
        env:
          CI_DIR: ${{github.workspace}}
          CI_DIR2: ${{github.workspace}}

      
          
